version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - SMTP_USERNAME=ysgaming2003@gmail.com
      - SMTP_PASSWORD=lvbq koun arsl tpln
      - KAFKA_BROKER=kafka:9092
